### ISSUE TITLE
Not clear how to import plugin

### ISSUE THREAD

**Issue by l29** [NotZoeyDev/Aliucord-Plugins#3]
Hi, nice project.
For me its not clear how to import plugins on IOS. it says copy link from the plugin.
For Example [SilentTyping](https://github.com/NotZoeyDev/Enmity-Plugins/tree/main/SilentTyping)
What link do i need to paste to import it.
Also keep this project on going : )

**Comment by Sylveondev** [comment]
The plugin needs to be compiled before you can use it.
